config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :articles
  resources :events
  resources :profiles
  resources :books
  resources :documents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/article.rb
class Article < ApplicationRecord
  enum :status, {
    draft: "draft", published: "published", archived: "archived"
  }, prefix: true

  include PgSearch::Model
  multisearchable(against: [:doc, :doc2], additional_attributes: ->(user) { { user_id: user.id } })


  def user
    User.first
  end
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title, against: :title
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :document

  include PgSearch

  pg_search_scope :search_title,
                  :against => [:title],
                  :using => [:tsearch, :dmetaphone, :trigrams],
                  :ignoring => :accents
end

app/models/comment.rb
class Comment < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:contents]
end

app/models/computer.rb
class Computer < ApplicationRecord
end

app/models/convertible.rb
class Convertible < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:make, :model],
                  if: :available_in_red?
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :book
  include PgSearch::Model
  multisearchable against: [:contents]

end

app/models/epic_poem.rb
class EpicPoem < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title, :author]
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/flower.rb
class Flower < ApplicationRecord
  include PgSearch::Model
  multisearchable against: :color
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/jalopy.rb
class Jalopy < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_full_name, against: [:first_name, :last_name]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:make, :model],
                  if: lambda { |record| record.model_year > 1970 }
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  include PgSearch::Model
  multisearchable(against: [:username],
                  additional_attributes: ->(user) { { user_id: user.id } })

  def user
    User.first
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy!

    respond_to do |format|
      format.html { redirect_to documents_path, status: :see_other, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:t)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <p>
    <strong>T:</strong>
    <%= document.t %>
  </p>

</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :t, style: "display: block" %>
    <%= form.text_field :t %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<% content_for :title, "Editing document" %>

<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Documents" %>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<% content_for :title, "New document" %>

<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @document %>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>